language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="graphql-async:. graphql-lwt:. graphql:."
  matrix:
  - PACKAGE="graphql.dev" OCAML_VERSION="4.03.0"
  - PACKAGE="graphql.dev" OCAML_VERSION="4.04.1"
  - PACKAGE="graphql-lwt.dev" OCAML_VERSION="4.03.0"
  - PACKAGE="graphql-lwt.dev" OCAML_VERSION="4.04.1"
  - PACKAGE="graphql-async.dev" OCAML_VERSION="4.03.0"
  - PACKAGE="graphql-async.dev" OCAML_VERSION="4.04.1"
